name: Main Push

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Main Project
        uses: actions/checkout@v4
        with:
          path: main-project

      - name: Checkout gradle-kit
        uses: actions/checkout@v4
        with:
          repository: jonloucks/gradle-kit
          path: gradle-kit

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Publish gradle-kit locally
        working-directory: gradle-kit
        run: ./gradlew publishToMavenLocal
        env:
          PROJECT_WORKFLOW: 'utility'

      - name: Build with Gradle
        working-directory: main-project
        run: ./gradlew build jacocoTestReport
        env:
          PROJECT_WORKFLOW: 'main-push'

      - name: Upload JaCoCo report artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: main-project/build/reports/jacoco/test/html/
